### ISSUE TITLE
The Fuwanovel Clannad patch doesn't work

### ISSUE THREAD

**Issue by eglaysher** [eglaysher/rlvm#56]
The reports from people complaining about the game locking up on the first voice call of the game all seem to be running the Fuwanovel patch.

```
(SEEN9600)(Line 30)[koePlay]: No such voice archive or sample
(SEEN9600)(Line 33)[strsub]: Error in strsub: offset is greater then string length
(SEEN9600)(Line 79)[strsub]: Error in strsub: offset is greater then string length
(SEEN9600)(Line 82)[strsub]: Error in strsub: offset is greater then string length
```

**Comment by UndeadMastodon** [comment]
Sorry about re-opening an old issue, but this issue seems to be with the rlvm interpreter. I am using the unofficial English patch for clannad and can confirm that it works in Windows (running the official REALLIVE.EXE interpreter) but not in Linux running rlvm. Is it that the patch relies on a bug in the official interpreter, or are you looking at it the wrong way (I'm sorry I am of little help when it comes to reading the bytecode as I am completely unfamiliar with it.)

Of course, if rlvm devs are completely done looking into it. I could attempt to fix it myself. If that's the case it'd be nice if anyone could refer me to any documentation as a starting point. The simplest workaround I can think of right now is to replace that whole section with no-ops (whatever serves as a no-op in reallive bytecode) and just skip it entirely (and of course hope that this issue does not re-appear.) This is of course a "fix" unrelated to rlvm.

Thanks beforehand.

**Comment by alexskc** [comment]
Seeing as Clannad is getting an official translation in the near future, there's not really much need to support the fan patch anymore.

**Comment by eglaysher** [comment]
> ... replace that whole section with no-ops (whatever serves as a no-op in reallive bytecode) and just skip it entirely (and of course hope that this issue does not re-appear.)

Such a workaround wouldn't be accepted; Clannad is licensed, and I don't want to add any patch specific workarounds in general.

Now, if you figure out the difference in behaviors between rlvm and the official interpreter, that's a different matter. One possibility that comes to mind is that maybe the reason the call stack has a maximum size, and on stack overflow, gosubs just fail. Testing that though would require having rldev installed, making a test case against the official interpreter to verify that that's whats going on though.

As a quick sanity check before you do that, you could see if refusing to gosub after some big number of stack frames fixes things (2048 is probably safe). You might also need to make sure that the instruction pointer gets implemented; I'm fuzzy as to whether this case would need manual instruction pointer advancement.

stack manipulation: https://github.com/eglaysher/rlvm/blob/master/src/machine/rlmachine.cc#L403
gosub opcode: https://github.com/eglaysher/rlvm/blob/master/src/modules/module_jmp.cc#L231

If you then want to make a test case, your best bet is rldev. This is documented here: http://dev.haeleth.net/rldev/manual.html
